# Uczenie maszynowe - Ćwiczenie 1 - NumPy - Zadania

**Zadanie 1**. Sprawdź do czego służą i przetestuj działanie następujących funkcji tworzących tablice `ndarray`:
1. `asarray`
2. `ones_like`
3. `zeros_like`
4. `full`
5. `full_like`
6. `eye`
7. `identity`

In [1]:
import numpy as np

In [2]:
a = [1,2,3,4,5,6,7]

In [3]:
#asarray

np.asarray(a)

array([1, 2, 3, 4, 5, 6, 7])

In [4]:
#one_like
#zero_like
x = np.arange(8)
x = x.reshape((2,4))
x

np.ones_like(x)

np.zeros_like(x)


array([[0, 0, 0, 0],
       [0, 0, 0, 0]])

In [5]:
#full
np.full((5,5), 12.3)

array([[12.3, 12.3, 12.3, 12.3, 12.3],
       [12.3, 12.3, 12.3, 12.3, 12.3],
       [12.3, 12.3, 12.3, 12.3, 12.3],
       [12.3, 12.3, 12.3, 12.3, 12.3],
       [12.3, 12.3, 12.3, 12.3, 12.3]])

In [6]:
y = np.arange(10, dtype = int).reshape(2, 5)

np.full_like(y, 10.0)

array([[10, 10, 10, 10, 10],
       [10, 10, 10, 10, 10]])

In [7]:
#eye
np.eye(3,6)

array([[1., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0.]])

In [8]:
#identity

np.identity(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

**Zadanie 2**. Sprawdź, w jaki sposób są konwertowane przez funkcję `astype` niecałkowite wartości zmiennoprzecinkowe na wartości całkowite.

In [9]:
arr = np.array([1.1, 2.1, 3.1])

newarr = arr.astype(int)

print(newarr)
print(newarr.dtype)  

[1 2 3]
int32


Szczegółowa informacja o typach wykorzystywanych w NumPy: https://numpy.org/doc/stable/reference/arrays.scalars.html#

**Zadanie 3**. Przekonwertuj tablicę wartości zmiennoprzecinkowych na tablicę stringów. Następnie przekonwertuj tablicę stringów z powrotem na wartości zmiennoprzecinkowe.

In [10]:

# Tablica wartości zmiennoprzecinkowych
float_array = np.array([3.14, 2.71, 1.41, 0.577, 1.618], dtype=np.float64)

# Konwersja na tablicę stringów
string_array = float_array.astype(str)
print("Tablica stringów:", string_array)

# Konwersja z powrotem na wartości zmiennoprzecinkowe
converted_float_array = string_array.astype(np.float64)
print("Tablica wartości zmiennoprzecinkowych:", converted_float_array)


Tablica stringów: ['3.14' '2.71' '1.41' '0.577' '1.618']
Tablica wartości zmiennoprzecinkowych: [3.14  2.71  1.41  0.577 1.618]


**Zadanie 4**. Zaprezentuj przykład rozgłaszania na dowolnej dwuargumentowej operacji gdzie pierwszym argumentem jest tablica trójwymiarowa, a drugim argumentem tablica dwuwymiarowa.

In [11]:
# Tworzymy tablicę 3D o kształcie (2, 3, 4)
array_3d = np.arange(24).reshape(2, 3, 4)
print("Tablica 3D:\n", array_3d)

# Tworzymy tablicę 2D o kształcie (3, 4)
array_2d = np.array([[10, 20, 30, 40], 
                      [50, 60, 70, 80], 
                      [90, 100, 110, 120]])
print("\nTablica 2D:\n", array_2d)

# Dodajemy tablicę 2D do tablicy 3D (broadcasting)
result = array_3d + array_2d
print("\nWynik dodawania z rozgłaszaniem:\n", result)

Tablica 3D:
 [[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]]

Tablica 2D:
 [[ 10  20  30  40]
 [ 50  60  70  80]
 [ 90 100 110 120]]

Wynik dodawania z rozgłaszaniem:
 [[[ 10  21  32  43]
  [ 54  65  76  87]
  [ 98 109 120 131]]

 [[ 22  33  44  55]
  [ 66  77  88  99]
  [110 121 132 143]]]


**Zadanie 5**. Przeczytaj w dokumentacji zastosowanie następujących metod a następnie przetestuj ich działanie na dowolnej tablicy dwuwymiarowej:
1. `sum`
2. `mean`
3. `std`
4. `var`
5. `min` 
6. `max`
7. `argmin`
8. `argmax`
9. `cumsum`
10. `cumprod`

In [12]:
array_2d = np.array([[1, 2, 3], 
                      [4, 5, 6], 
                      [7, 8, 9]])

print("Tablica 2D:\n", array_2d)

print("Suma całej tablicy:", array_2d.sum())



print("Średnia całej tablicy:", array_2d.mean())


print("Odchylenie standardowe całej tablicy:", array_2d.std())



print("Wariancja całej tablicy:", array_2d.var())


print("Minimalna wartość w tablicy:", array_2d.min())



print("Maksymalna wartość w tablicy:", array_2d.max())



print("Indeks najmniejszego elementu (w 1D):", array_2d.argmin())



print("Indeks największego elementu (w 1D):", array_2d.argmax())



print("Skumulowana suma całej tablicy:", array_2d.cumsum())



print("Skumulowany iloczyn całej tablicy:", array_2d.cumprod())



Tablica 2D:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
Suma całej tablicy: 45
Średnia całej tablicy: 5.0
Odchylenie standardowe całej tablicy: 2.581988897471611
Wariancja całej tablicy: 6.666666666666667
Minimalna wartość w tablicy: 1
Maksymalna wartość w tablicy: 9
Indeks najmniejszego elementu (w 1D): 0
Indeks największego elementu (w 1D): 8
Skumulowana suma całej tablicy: [ 1  3  6 10 15 21 28 36 45]
Skumulowany iloczyn całej tablicy: [     1      2      6     24    120    720   5040  40320 362880]


**Zadanie 8.** Wygeneruj wektor stworzony z wektora [1, 2, 3], aby każdy element powtarzał się 4 razy i taka sekwencja była powtórzona 3-krotnie.

In [13]:
vector = np.array([1, 2, 3])

repeated_elements = np.repeat(vector, 4)

final_vector = np.tile(repeated_elements, 3)

print(final_vector)

[1 1 1 1 2 2 2 2 3 3 3 3 1 1 1 1 2 2 2 2 3 3 3 3 1 1 1 1 2 2 2 2 3 3 3 3]


**Zadanie 9.** Wygeneruj wektor wartości od 1 do 10 co 0.25.

In [14]:
np.arange(1,10,0.25)

array([1.  , 1.25, 1.5 , 1.75, 2.  , 2.25, 2.5 , 2.75, 3.  , 3.25, 3.5 ,
       3.75, 4.  , 4.25, 4.5 , 4.75, 5.  , 5.25, 5.5 , 5.75, 6.  , 6.25,
       6.5 , 6.75, 7.  , 7.25, 7.5 , 7.75, 8.  , 8.25, 8.5 , 8.75, 9.  ,
       9.25, 9.5 , 9.75])

**Zadanie 10.** Wygeneruj wektor 43 wartości równomiernie  od 1 do 10.

In [15]:
vector = np.linspace(1, 10, 43)

print(vector)


[ 1.          1.21428571  1.42857143  1.64285714  1.85714286  2.07142857
  2.28571429  2.5         2.71428571  2.92857143  3.14285714  3.35714286
  3.57142857  3.78571429  4.          4.21428571  4.42857143  4.64285714
  4.85714286  5.07142857  5.28571429  5.5         5.71428571  5.92857143
  6.14285714  6.35714286  6.57142857  6.78571429  7.          7.21428571
  7.42857143  7.64285714  7.85714286  8.07142857  8.28571429  8.5
  8.71428571  8.92857143  9.14285714  9.35714286  9.57142857  9.78571429
 10.        ]


**Zadanie 11.** Wyświetl co trzeci element z powyższego wektora.

In [16]:
vector[::3]

array([ 1.        ,  1.64285714,  2.28571429,  2.92857143,  3.57142857,
        4.21428571,  4.85714286,  5.5       ,  6.14285714,  6.78571429,
        7.42857143,  8.07142857,  8.71428571,  9.35714286, 10.        ])

**Zadanie 12.** Wyjaśnij wynik działania komendy `np.arange(6) – 1`

In [17]:
np.arange(6) -1

#od każdego elementu odejmowane jest 1

array([-1,  0,  1,  2,  3,  4])

**Zadanie 13.** Utwórz macierz o 3 wierszach i 2 kolumnach poprzez:  
1. wypełnienie jej wierszowo wektorem (1,2,3,4,5,6),  
1. wypełnienie jej kolumnowo wektorem (1,2,3,4,5,6),  
1. złożenie wektorów (1,2,3) i (4,5,6),  
1. złożenie wektorów (1,4), (2,5) i (3,6).  

In [18]:
vector1 = np.array([1, 2, 3, 4, 5, 6])

matrix1 = vector1.reshape(3, 2)

print("Macierz wypełniona wierszowo:\n", matrix1)

Macierz wypełniona wierszowo:
 [[1 2]
 [3 4]
 [5 6]]


In [19]:
vector2 = np.array([1, 2, 3, 4, 5, 6])

matrix2 = vector2.reshape(2, 3).T
print("Macierz wypełniona kolumnowo:\n", matrix2)


Macierz wypełniona kolumnowo:
 [[1 4]
 [2 5]
 [3 6]]


In [20]:
vector3 = np.array([1, 2, 3])
vector4 = np.array([4, 5, 6])

matrix3 = np.vstack((vector3, vector4))
print("Złożenie wektorów (1,2,3) i (4,5,6):\n", matrix3)


Złożenie wektorów (1,2,3) i (4,5,6):
 [[1 2 3]
 [4 5 6]]


In [21]:
vector5 = np.array([1, 4])
vector6 = np.array([2, 5])
vector7 = np.array([3, 6])

matrix4 = np.column_stack((vector5, vector6, vector7))
print("Złożenie wektorów (1,4), (2,5), (3,6):\n", matrix4)


Złożenie wektorów (1,4), (2,5), (3,6):
 [[1 2 3]
 [4 5 6]]


**Zadanie 14.** Utwórz macierz A o 6 wierszach i 6 kolumnach wypełnioną wierszowo liczbami od 1 do 36. Następnie korzystając z indeksowania utwórz macierz B:
1. o 3 wierszach i 3 kolumnach zawierającą elementy z wierszy o parzystych numerach i kolumn o nieparzystych numerach z macierzy A, przy czym kolumny w odwrotnej kolejności, czyli: pierwszy wiersz macierzy B będzie zawierał liczby 11, 9, 7, drugi 23, 21, 19, a trzeci 35, 33 i 31,
1. składającą się z dwóch ostatnich wierszy macierzy A,
1. składającą się z dwóch środkowych kolumn macierzy A,

In [22]:
# Step 1: Create Matrix A
A = np.arange(1, 37).reshape(6, 6)

# Part 1: Extract even rows and reversed odd columns
B1 = A[1::2, [4, 2, 0]] 

# Part 2: Extract last two rows
B2 = A[-2:, :]

# Part 3: Extract two middle columns
B3 = A[:, 2:4]

# Print results
print("Matrix A:")
print(A)
print("\nMatrix B1:")
print(B1)
print("\nMatrix B2:")
print(B2)
print("\nMatrix B3:")
print(B3)

Matrix A:
[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]
 [13 14 15 16 17 18]
 [19 20 21 22 23 24]
 [25 26 27 28 29 30]
 [31 32 33 34 35 36]]

Matrix B1:
[[11  9  7]
 [23 21 19]
 [35 33 31]]

Matrix B2:
[[25 26 27 28 29 30]
 [31 32 33 34 35 36]]

Matrix B3:
[[ 3  4]
 [ 9 10]
 [15 16]
 [21 22]
 [27 28]
 [33 34]]


**Zadanie 15**. Posortuj poniższą tablicę w wierszach.

In [23]:
T = np.array([[5,2,1,6],[4,8,3,1],[2,4,7,8]])
T_sorted = np.sort(T, axis=1)
print(T_sorted)

[[1 2 5 6]
 [1 3 4 8]
 [2 4 7 8]]


**Zadanie 16**. Posortuj powyższą tablicę w kolumnach.

In [24]:
T_sorted_columns = np.sort(T, axis=0)
print(T_sorted_columns)

[[2 2 1 1]
 [4 4 3 6]
 [5 8 7 8]]


**Zadanie 17**. Za pomocą `np.argsort()` podaj numery elementów oryginalnej tablicy w każdym wierszu, gdyby była ona posortowana w wierszach.

In [25]:
row_indices = np.argsort(T, axis=1)
print(row_indices)

[[2 1 0 3]
 [3 2 0 1]
 [0 1 2 3]]


**Zadanie 18**. Poniższą tablicę posortuj zgodnie z porządkiem leksykograficznym na podstawie kolumny drugiej, w następnej kolejności na podstawie kolumny czwartej, a ostatecznie szóstej.

In [26]:
T = np.array([[5,2,5,2,7,4],[2,2,1,5,4,3],[1,3,4,1,4,5],[1,3,1,1,2,2]])

keys = (T[:,5],   
        T[:,3],   
        T[:,1])  

sorted_indices = np.lexsort(keys)

sorted_T = T[sorted_indices]

print(sorted_T)

[[5 2 5 2 7 4]
 [2 2 1 5 4 3]
 [1 3 1 1 2 2]
 [1 3 4 1 4 5]]


**Zadanie 19**. Za pomocą `np.hsplit()` podziel powyższą tablicę na 3 równe części.

In [27]:
split_arrays = np.hsplit(T, 3)

for i, subarray in enumerate(split_arrays):
    print(f"Tablica {i+1}:\n", subarray)

Tablica 1:
 [[5 2]
 [2 2]
 [1 3]
 [1 3]]
Tablica 2:
 [[5 2]
 [1 5]
 [4 1]
 [1 1]]
Tablica 3:
 [[7 4]
 [4 3]
 [4 5]
 [2 2]]


**Zadanie 20**. Za pomocą `np.hsplit()` podziel powyższą tablicę na 4 części tak, aby w pierwszej , trzeciej i czwartej części znalazła się tylko jedna kolumna, a w drugiej części 3 kolumny.

In [28]:
split_arrays_next = np.hsplit(T, [1,4,5])

for i, subarray in enumerate(split_arrays_next):
    print(f"Tablica {i+1}:\n", subarray)

Tablica 1:
 [[5]
 [2]
 [1]
 [1]]
Tablica 2:
 [[2 5 2]
 [2 1 5]
 [3 4 1]
 [3 1 1]]
Tablica 3:
 [[7]
 [4]
 [4]
 [2]]
Tablica 4:
 [[4]
 [3]
 [5]
 [2]]


**Zadanie 21**. Za pomocą `np.vsplit()` podziel powyższą tablicę na 3 dowolne części.

In [29]:
T_split = np.vsplit(T, [2,3])

for i, subarray in enumerate(T_split):
    print(f"Tablica {i+1}:\n", subarray)

Tablica 1:
 [[5 2 5 2 7 4]
 [2 2 1 5 4 3]]
Tablica 2:
 [[1 3 4 1 4 5]]
Tablica 3:
 [[1 3 1 1 2 2]]


**Zadanie 22**. W trzech powyższych zadaniach, po podziale scal z powrotem części w jedną tablicę za pomocą `np.vstack()` lub `np.hstack()`.

In [30]:
T_stack = np.vstack(T_split)
print(T_stack)

[[5 2 5 2 7 4]
 [2 2 1 5 4 3]
 [1 3 4 1 4 5]
 [1 3 1 1 2 2]]


**Zadanie 23**. Co robi z wektorem *w* poniższa operacja?

In [31]:
w = np.arange(1,11)
w1 = w[:, np.newaxis]
print(w1)

[[ 1]
 [ 2]
 [ 3]
 [ 4]
 [ 5]
 [ 6]
 [ 7]
 [ 8]
 [ 9]
 [10]]


**Zadanie 24**. Co stanie się, jeżeli w powyszej opercji zamienimy pozycje indeksowania?

In [32]:
w = np.arange(1,11)
w2 = w[np.newaxis, :]
print(w)

[ 1  2  3  4  5  6  7  8  9 10]


**Zadanie 25**. Korzystając z powyższego wektora i operatora `*`, wykorzystaj rozgłaszanie do wyliczenia tabliczki mnożenia do 100.

In [33]:
tabliczka = w1*w2
print(tabliczka)

[[  1   2   3   4   5   6   7   8   9  10]
 [  2   4   6   8  10  12  14  16  18  20]
 [  3   6   9  12  15  18  21  24  27  30]
 [  4   8  12  16  20  24  28  32  36  40]
 [  5  10  15  20  25  30  35  40  45  50]
 [  6  12  18  24  30  36  42  48  54  60]
 [  7  14  21  28  35  42  49  56  63  70]
 [  8  16  24  32  40  48  56  64  72  80]
 [  9  18  27  36  45  54  63  72  81  90]
 [ 10  20  30  40  50  60  70  80  90 100]]


**Zadanie 26**. Wykorzystaj funkcję `np.nonzero()` aby uzyskać indeksy wierszy i kolumn wszystkich elementów z tablicy z zadania 10, która są jednocześnie nie mniejsze od 2 i mniejsze od 7. Wypisz wszystkie takie pary (nr_wiersza, nr_kolumny) na ekranie (podpowiedź: komenda `zip`).

In [34]:
vector64 = np.linspace(1, 10, 43)

indices = np.nonzero((vector64 >= 2) & (vector64 < 7))[0]

for index, value in zip(indices, vector64[indices]):
    print(f"({index}, {value:.2f})")

(5, 2.07)
(6, 2.29)
(7, 2.50)
(8, 2.71)
(9, 2.93)
(10, 3.14)
(11, 3.36)
(12, 3.57)
(13, 3.79)
(14, 4.00)
(15, 4.21)
(16, 4.43)
(17, 4.64)
(18, 4.86)
(19, 5.07)
(20, 5.29)
(21, 5.50)
(22, 5.71)
(23, 5.93)
(24, 6.14)
(25, 6.36)
(26, 6.57)
(27, 6.79)


**Zadanie 27**. Korzystając z `np.unique()`, w poniższym wektorze znajdź wszystkie elementy unikatowe, ich indeksy oraz liczbę powtórzeń każdego z nich.

In [35]:
w = np.array([1,2,2,2,3,1,3,1,4,4,5,6,5,7,8,8])

In [36]:
unique_values, indices, counts = np.unique(w, return_index=True, return_counts=True)

# Wyświetl wyniki
print("Unikalne wartości:", unique_values)
print("Indeksy pierwszego wystąpienia:", indices)
print("Liczba powtórzeń:", counts)



Unikalne wartości: [1 2 3 4 5 6 7 8]
Indeksy pierwszego wystąpienia: [ 0  1  4  8 10 11 13 14]
Liczba powtórzeń: [3 3 2 2 2 1 1 2]


**Zadanie 28**. Korzystając z `np.unique()`, w poniższej tablicy znajdź wszystkie unikatowe wiersze, ich indeksy oraz liczbę powtórzeń każdego z nich.

In [37]:
T = np.array([[1,2],[2,1],[2,2],[2,2],[2,3],[3,2],[1,2],[1,4],[2,1]])

unique_rows, indices, counts = np.unique(T, axis=0, return_index=True, return_counts=True)

print("Unikalne wiersze:")
print(unique_rows)
print("\nIndeksy pierwszych wystąpień:", indices)
print("Liczba powtórzeń:", counts)

Unikalne wiersze:
[[1 2]
 [1 4]
 [2 1]
 [2 2]
 [2 3]
 [3 2]]

Indeksy pierwszych wystąpień: [0 7 1 2 4 5]
Liczba powtórzeń: [2 1 2 2 1 1]


**Zadanie 29** (*). Podczas ostatniego wykładu podano cztery sposoby liczenia odległości między klastrami. Wczytaj klastry z plików `klaster A.csv`, `klaster B.csv` i `klaster C.csv` za pomocą `np.loadtxt()`. Następnie wylicz odległości między każdą parą klastrów na każdy z czterech sposobów korzystając z możliwości NumPy. 

**Zadanie 30** (*). Dla każdego sposobu pomiaru odległości pomiędzy klastrami wylicz miarę $wc(C)/bc(C)$.